### ISSUE TITLE
what is NEWOPERATORS and how to set it

### ISSUE THREAD

**Issue by Ruturaj4** [RUB-SysSec/Marx#1]
Hello,

I built marx and also ran idapython script to excavate necessary data. But, I noticed that in the config file you used a variable called NEWOPERATORS. I couldn't find more information about this in the description (nor in the paper). Could you kindly explain what is it and what parameters to set?

**Comment by sqall01** [comment]
You need to set the address to the "new" function there. In C++ this would be the function that is executed when you use the "new" operator. Something you can find easily with IDA since the symbol is in the binary. If I recall correctly, it was not automated since you can set the function addresses of custom heap allocators there (the only important thing is that the address of the new memory object is returned by this function).

**Comment by Ruturaj4** [comment]
got it thanks!
